# Generated by Django 3.2 on 2023-03-07 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_num', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('paient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='patient')),
            ],
        ),
    ]
