# Generated by Django 3.2 on 2023-03-07 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role_app', '0002_paient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paient',
            name='paient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_User', to=settings.AUTH_USER_MODEL, verbose_name='patient'),
        ),
    ]
