# Generated by Django 3.2 on 2023-03-09 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role_app', '0003_alter_paient_paient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_User', to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
            ],
        ),
    ]
